databases:
  - name: Dentdb
    plan: free
    databaseName: Dent
    user: Dent

services:
  - type: web
    plan: free
    name: Dent
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Dent.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Dentdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4